import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'ARF – Agentic Reliability Framework',
  description: 'Bayesian governance for agentic systems',
  manifest: '/site.webmanifest',
  themeColor: '#3b82f6',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'ARF',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon links generated by RealFaviconGenerator */}
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
        {/* Additional PWA meta tags */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>
      <body className="min-h-screen bg-gray-100">
        <nav className="bg-gray-800 text-white shadow-md" aria-label="Main navigation">
          <div className="container mx-auto flex items-center gap-6 p-4">
            <Link href="/" className="font-bold hover:underline">ARF</Link>
            <Link href="/dashboard" className="hover:underline">Dashboard</Link>
            <Link href="/history" className="hover:underline">History</Link>
            <a
              href="https://arf-foundation.github.io/arf-spec/"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline ml-auto"
            >
              Documentation
            </a>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
