name: Test Frontend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install   # removed --frozen-lockfile
      - name: Upload yarn.lock
        uses: actions/upload-artifact@v4
        with:
          name: yarn-lock
          path: yarn.lock
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
